/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Design;

import jaco.mp3.player.MP3Player;
import mp3Player.*;
import java.io.File;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.filechooser.FileNameExtensionFilter;

/**
 *
 * @author Big Nigga Dude
 */
public class Player extends javax.swing.JFrame {

    MP3Player player;
    File songFile;
    PlayerSet myPlayer = new PlayerSet();
    String nowPlaying = "Sedang Diputar : ";
    boolean paused = false;

    public Player() {
        initComponents();
        songFile = new File("E:\\Musik\\Berita Angkasa.mp3");
        String fileName = songFile.getName();
        player = myPlayer.setPlayer();
        player.addToPlayList(songFile);
        nowPlayingLbl.setText(nowPlaying + fileName);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        nowPlayingLbl = new javax.swing.JLabel();
        playBtn = new javax.swing.JLabel();
        stopBtn = new javax.swing.JLabel();
        openBtn = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(102, 0, 102));

        nowPlayingLbl.setBackground(new java.awt.Color(0, 0, 0));
        nowPlayingLbl.setFont(new java.awt.Font("Swis721 LtEx BT", 1, 14)); // NOI18N
        nowPlayingLbl.setForeground(new java.awt.Color(255, 255, 255));
        nowPlayingLbl.setText("jLabel1");

        playBtn.setBackground(new java.awt.Color(204, 153, 0));
        playBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/res/Media-Play-52.png"))); // NOI18N
        playBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        playBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                playBtnMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                playBtnMouseEntered(evt);
            }
        });
        playBtn.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                playBtnKeyPressed(evt);
            }
        });

        stopBtn.setBackground(new java.awt.Color(204, 153, 0));
        stopBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/res/Stop-Media-52.png"))); // NOI18N
        stopBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        stopBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                stopBtnMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                stopBtnMouseEntered(evt);
            }
        });
        stopBtn.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                stopBtnKeyPressed(evt);
            }
        });

        openBtn.setBackground(new java.awt.Color(204, 153, 0));
        openBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/res/Folder-Open-01-56.png"))); // NOI18N
        openBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        openBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                openBtnMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                openBtnMouseEntered(evt);
            }
        });
        openBtn.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                openBtnKeyPressed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(nowPlayingLbl))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(115, 115, 115)
                        .addComponent(playBtn)
                        .addGap(102, 102, 102)
                        .addComponent(stopBtn)
                        .addGap(81, 81, 81)
                        .addComponent(openBtn)))
                .addContainerGap(156, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addComponent(nowPlayingLbl)
                .addGap(26, 26, 26)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(openBtn)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(stopBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(playBtn))))
                .addContainerGap(80, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void playBtnKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_playBtnKeyPressed

    }//GEN-LAST:event_playBtnKeyPressed

    private void playBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_playBtnMouseClicked
        // TODO add your handling code here:
        if (!paused) {
            playBtn.setIcon(new ImageIcon("src/res/Media-Pause-52.png"));
            paused = true;
            player.play();
        } else {
            playBtn.setIcon(new ImageIcon("src/res/Media-Play-52.png"));
            paused = false; 
            player.pause();
        }
    }//GEN-LAST:event_playBtnMouseClicked

    private void playBtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_playBtnMouseEntered
        // TODO add your handling code here:

    }//GEN-LAST:event_playBtnMouseEntered

    private void stopBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_stopBtnMouseClicked
        player.stop();
        paused = false;
        playBtn.setIcon(new ImageIcon("src/res/Media-Play-52.png"));
    }//GEN-LAST:event_stopBtnMouseClicked

    private void stopBtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_stopBtnMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_stopBtnMouseEntered

    private void stopBtnKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_stopBtnKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_stopBtnKeyPressed

    private void openBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_openBtnMouseClicked
        JFileChooser openFile = new JFileChooser("E:/");
        FileNameExtensionFilter filter = new FileNameExtensionFilter("MPEG3 songs", "mp3");
        openFile.addChoosableFileFilter(filter);
        int res = openFile.showOpenDialog(null);
        if (res == JFileChooser.APPROVE_OPTION) {
            songFile = openFile.getSelectedFile();
            player.addToPlayList(songFile);
            player.skipForward();
            player.play();
            playBtn.setIcon(new ImageIcon("src/res/Media-Pause-52.png"));
            nowPlayingLbl.setText(nowPlaying + songFile.getName());
        }
    }//GEN-LAST:event_openBtnMouseClicked

    private void openBtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_openBtnMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_openBtnMouseEntered

    private void openBtnKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_openBtnKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_openBtnKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Player.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Player.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Player.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Player.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        Player p = new Player();
        p.setLocationRelativeTo(null);
        p.setResizable(false);
        p.setTitle("Azriel Mp3 Player");
        p.setVisible(true);
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel nowPlayingLbl;
    private javax.swing.JLabel openBtn;
    private javax.swing.JLabel playBtn;
    private javax.swing.JLabel stopBtn;
    // End of variables declaration//GEN-END:variables
}
